// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://foottpeomzltpxhaujwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvb3R0cGVvbXpsdHB4aGF1andhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NTY2MjMsImV4cCI6MjA2MDAzMjYyM30.m8mnbeHQj7J82NckNboinbrJSqXNfe29LDRjUy67OVM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);